
let city = [
    {
        "title":"热门城市",
        "type":"hot",
        "item":[
            {
                "name":"北京",
                "key":"热门"
            },
            {
                "name":"上海",
                "key":"热门"
            },
            {
                "name":"广州",
                "key":"热门"
            },
            {
                "name":"深圳",
                "key":"热门"
            },
            {
                "name":"成都",
                "key":"热门"
            },
            {
                "name":"重庆",
                "key":"热门"
            },
            {
                "name":"天津",
                "key":"热门"
            },
            {
                "name":"杭州",
                "key":"热门"
            },
            {
                "name":"南京",
                "key":"热门"
            },
            {
                "name":"苏州",
                "key":"热门"
            },
            {
                "name":"武汉",
                "key":"热门"
            },
            {
                "name":"西安",
                "key":"热门"
            },
            {
                "name":"海外",
                "key":"热门"
            }
        ]
    },
    {
        "title":"A",
        "item":[
            {
                "name":"阿拉善盟",
                "key":"A"
            },
            {
                "name":"鞍山市",
                "key":"A"
            },
            {
                "name":"安庆市",
                "key":"A"
            },
            {
                "name":"安阳市",
                "key":"A"
            },
            {
                "name":"阿坝藏族羌族自治州",
                "key":"A"
            },
            {
                "name":"安顺市",
                "key":"A"
            },
            {
                "name":"阿里地区",
                "key":"A"
            },
            {
                "name":"安康市",
                "key":"A"
            },
            {
                "name":"阿克苏地区",
                "key":"A"
            },
            {
                "name":"阿勒泰地区",
                "key":"A"
            },
            {
                "name":"阿拉尔市",
                "key":"A"
            },
            {
                "name":"澳门半岛",
                "key":"A"
            }
        ]
    },
    {
        "title":"B",
        "item":[
            {
                "name":"北京市",
                "key":"B"
            },
            {
                "name":"保定市",
                "key":"B"
            },
            {
                "name":"包头市",
                "key":"B"
            },
            {
                "name":"巴彦淖尔市",
                "key":"B"
            },
            {
                "name":"本溪市",
                "key":"B"
            },
            {
                "name":"白山市",
                "key":"B"
            },
            {
                "name":"白城市",
                "key":"B"
            },
            {
                "name":"蚌埠市",
                "key":"B"
            },
            {
                "name":"滨州市",
                "key":"B"
            },
            {
                "name":"北海市",
                "key":"B"
            },
            {
                "name":"百色市",
                "key":"B"
            },
            {
                "name":"白沙黎族自治县",
                "key":"B"
            },
            {
                "name":"保亭黎族苗族自治县",
                "key":"B"
            },
            {
                "name":"巴中市",
                "key":"B"
            },
            {
                "name":"毕节地区",
                "key":"B"
            },
            {
                "name":"保山市",
                "key":"B"
            },
            {
                "name":"宝鸡市",
                "key":"B"
            },
            {
                "name":"白银市",
                "key":"B"
            },
            {
                "name":"博尔塔拉蒙古自治州",
                "key":"B"
            },
            {
                "name":"巴音郭楞蒙古自治州",
                "key":"B"
            }
        ]
    },
    {
        "title":"C",
        "item":[
            {
                "name":"承德市",
                "key":"C"
            },
            {
                "name":"沧州市",
                "key":"C"
            },
            {
                "name":"长治市",
                "key":"C"
            },
            {
                "name":"赤峰市",
                "key":"C"
            },
            {
                "name":"朝阳市",
                "key":"C"
            },
            {
                "name":"长春市",
                "key":"C"
            },
            {
                "name":"常州市",
                "key":"C"
            },
            {
                "name":"滁州市",
                "key":"C"
            },
            {
                "name":"池州市",
                "key":"C"
            },
            {
                "name":"长沙市",
                "key":"C"
            },
            {
                "name":"常德市",
                "key":"C"
            },
            {
                "name":"郴州市",
                "key":"C"
            },
            {
                "name":"潮州市",
                "key":"C"
            },
            {
                "name":"崇左市",
                "key":"C"
            },
            {
                "name":"澄迈县",
                "key":"C"
            },
            {
                "name":"昌江黎族自治县",
                "key":"C"
            },
            {
                "name":"成都市",
                "key":"C"
            },
            {
                "name":"楚雄彝族自治州",
                "key":"C"
            },
            {
                "name":"昌都地区",
                "key":"C"
            },
            {
                "name":"昌吉回族自治州",
                "key":"C"
            }
        ]
    },
    {
        "title":"D",
        "item":[
            {
                "name":"大同市",
                "key":"D"
            },
            {
                "name":"大连市",
                "key":"D"
            },
            {
                "name":"丹东市",
                "key":"D"
            },
            {
                "name":"大庆市",
                "key":"D"
            },
            {
                "name":"大兴安岭地区",
                "key":"D"
            },
            {
                "name":"东营市",
                "key":"D"
            },
            {
                "name":"德州市",
                "key":"D"
            },
            {
                "name":"东莞市",
                "key":"D"
            },
            {
                "name":"东方市",
                "key":"D"
            },
            {
                "name":"定安县",
                "key":"D"
            },
            {
                "name":"德阳市",
                "key":"D"
            },
            {
                "name":"达州市",
                "key":"D"
            },
            {
                "name":"大理白族自治州",
                "key":"D"
            },
            {
                "name":"德宏傣族景颇族自治州",
                "key":"D"
            },
            {
                "name":"迪庆藏族自治州",
                "key":"D"
            },
            {
                "name":"定西市",
                "key":"D"
            }
        ]
    },
    {
        "title":"E",
        "item":[
            {
                "name":"鄂尔多斯市",
                "key":"E"
            },
            {
                "name":"鄂州市",
                "key":"E"
            },
            {
                "name":"恩施土家族苗族自治州",
                "key":"E"
            }
        ]
    },
    {
        "title":"F",
        "item":[
            {
                "name":"抚顺市",
                "key":"F"
            },
            {
                "name":"阜新市",
                "key":"F"
            },
            {
                "name":"阜阳市",
                "key":"F"
            },
            {
                "name":"福州市",
                "key":"F"
            },
            {
                "name":"抚州市",
                "key":"F"
            },
            {
                "name":"佛山市",
                "key":"F"
            },
            {
                "name":"防城港市",
                "key":"F"
            }
        ]
    },
    {
        "title":"G",
        "item":[
            {
                "name":"赣州市",
                "key":"G"
            },
            {
                "name":"广州市",
                "key":"G"
            },
            {
                "name":"桂林市",
                "key":"G"
            },
            {
                "name":"贵港市",
                "key":"G"
            },
            {
                "name":"广元市",
                "key":"G"
            },
            {
                "name":"广安市",
                "key":"G"
            },
            {
                "name":"甘孜藏族自治州",
                "key":"G"
            },
            {
                "name":"贵阳市",
                "key":"G"
            },
            {
                "name":"甘南藏族自治州",
                "key":"G"
            },
            {
                "name":"果洛藏族自治州",
                "key":"G"
            },
            {
                "name":"固原市",
                "key":"G"
            },
            {
                "name":"高雄市",
                "key":"G"
            }
        ]
    },
    {
        "title":"H",
        "item":[
            {
                "name":"邯郸市",
                "key":"H"
            },
            {
                "name":"衡水市",
                "key":"H"
            },
            {
                "name":"呼和浩特市",
                "key":"H"
            },
            {
                "name":"呼伦贝尔市",
                "key":"H"
            },
            {
                "name":"葫芦岛市",
                "key":"H"
            },
            {
                "name":"哈尔滨市",
                "key":"H"
            },
            {
                "name":"鹤岗市",
                "key":"H"
            },
            {
                "name":"黑河市",
                "key":"H"
            },
            {
                "name":"淮安市",
                "key":"H"
            },
            {
                "name":"杭州市",
                "key":"H"
            },
            {
                "name":"湖州市",
                "key":"H"
            },
            {
                "name":"合肥市",
                "key":"H"
            },
            {
                "name":"淮南市",
                "key":"H"
            },
            {
                "name":"淮北市",
                "key":"H"
            },
            {
                "name":"黄山市",
                "key":"H"
            },
            {
                "name":"菏泽市",
                "key":"H"
            },
            {
                "name":"鹤壁市",
                "key":"H"
            },
            {
                "name":"黄石市",
                "key":"H"
            },
            {
                "name":"黄冈市",
                "key":"H"
            },
            {
                "name":"衡阳市",
                "key":"H"
            },
            {
                "name":"怀化市",
                "key":"H"
            },
            {
                "name":"惠州市",
                "key":"H"
            },
            {
                "name":"河源市",
                "key":"H"
            },
            {
                "name":"贺州市",
                "key":"H"
            },
            {
                "name":"河池市",
                "key":"H"
            },
            {
                "name":"海口市",
                "key":"H"
            },
            {
                "name":"红河哈尼族彝族自治州",
                "key":"H"
            },
            {
                "name":"汉中市",
                "key":"H"
            },
            {
                "name":"海东地区",
                "key":"H"
            },
            {
                "name":"海北藏族自治州",
                "key":"H"
            },
            {
                "name":"黄南藏族自治州",
                "key":"H"
            },
            {
                "name":"海南藏族自治州",
                "key":"H"
            },
            {
                "name":"海西蒙古族藏族自治州",
                "key":"H"
            },
            {
                "name":"哈密地区",
                "key":"H"
            },
            {
                "name":"和田地区",
                "key":"H"
            },
            {
                "name":"花莲县",
                "key":"H"
            },
            {
                "name":"海外",
                "key":"H"
            }
        ]
    },
    {
        "title":"J",
        "item":[
            {
                "name":"晋城市",
                "key":"J"
            },
            {
                "name":"晋中市",
                "key":"J"
            },
            {
                "name":"锦州市",
                "key":"J"
            },
            {
                "name":"吉林市",
                "key":"J"
            },
            {
                "name":"鸡西市",
                "key":"J"
            },
            {
                "name":"佳木斯市",
                "key":"J"
            },
            {
                "name":"嘉兴市",
                "key":"J"
            },
            {
                "name":"金华市",
                "key":"J"
            },
            {
                "name":"景德镇市",
                "key":"J"
            },
            {
                "name":"九江市",
                "key":"J"
            },
            {
                "name":"吉安市",
                "key":"J"
            },
            {
                "name":"济南市",
                "key":"J"
            },
            {
                "name":"济宁市",
                "key":"J"
            },
            {
                "name":"焦作市",
                "key":"J"
            },
            {
                "name":"济源市",
                "key":"J"
            },
            {
                "name":"荆门市",
                "key":"J"
            },
            {
                "name":"荆州市",
                "key":"J"
            },
            {
                "name":"江门市",
                "key":"J"
            },
            {
                "name":"揭阳市",
                "key":"J"
            },
            {
                "name":"嘉峪关市",
                "key":"J"
            },
            {
                "name":"金昌市",
                "key":"J"
            },
            {
                "name":"酒泉市",
                "key":"J"
            },
            {
                "name":"金门县",
                "key":"J"
            },
            {
                "name":"基隆市",
                "key":"J"
            },
            {
                "name":"嘉义市",
                "key":"J"
            },
            {
                "name":"嘉义县",
                "key":"J"
            },
            {
                "name":"九龙",
                "key":"J"
            }
        ]
    },
    {
        "title":"K",
        "item":[
            {
                "name":"开封市",
                "key":"K"
            },
            {
                "name":"昆明市",
                "key":"K"
            },
            {
                "name":"克拉玛依市",
                "key":"K"
            },
            {
                "name":"克孜勒苏柯尔克孜自治州",
                "key":"K"
            },
            {
                "name":"喀什地区",
                "key":"K"
            }
        ]
    },
    {
        "title":"L",
        "item":[
            {
                "name":"廊坊市",
                "key":"L"
            },
            {
                "name":"临汾市",
                "key":"L"
            },
            {
                "name":"吕梁市",
                "key":"L"
            },
            {
                "name":"辽阳市",
                "key":"L"
            },
            {
                "name":"辽源市",
                "key":"L"
            },
            {
                "name":"连云港市",
                "key":"L"
            },
            {
                "name":"丽水市",
                "key":"L"
            },
            {
                "name":"六安市",
                "key":"L"
            },
            {
                "name":"龙岩市",
                "key":"L"
            },
            {
                "name":"莱芜市",
                "key":"L"
            },
            {
                "name":"临沂市",
                "key":"L"
            },
            {
                "name":"聊城市",
                "key":"L"
            },
            {
                "name":"洛阳市",
                "key":"L"
            },
            {
                "name":"娄底市",
                "key":"L"
            },
            {
                "name":"柳州市",
                "key":"L"
            },
            {
                "name":"来宾市",
                "key":"L"
            },
            {
                "name":"临高县",
                "key":"L"
            },
            {
                "name":"乐东黎族自治县",
                "key":"L"
            },
            {
                "name":"陵水黎族自治县",
                "key":"L"
            },
            {
                "name":"乐山市",
                "key":"L"
            },
            {
                "name":"凉山彝族自治州",
                "key":"L"
            },
            {
                "name":"六盘水市",
                "key":"L"
            },
            {
                "name":"丽江市",
                "key":"L"
            },
            {
                "name":"临沧市",
                "key":"L"
            },
            {
                "name":"拉萨市",
                "key":"L"
            },
            {
                "name":"林芝地区",
                "key":"L"
            },
            {
                "name":"兰州市",
                "key":"L"
            },
            {
                "name":"陇南市",
                "key":"L"
            },
            {
                "name":"临夏回族自治州",
                "key":"L"
            },
            {
                "name":"离岛",
                "key":"L"
            }
        ]
    },
    {
        "title":"M",
        "item":[
            {
                "name":"牡丹江市",
                "key":"M"
            },
            {
                "name":"马鞍山市",
                "key":"M"
            },
            {
                "name":"茂名市",
                "key":"M"
            },
            {
                "name":"梅州市",
                "key":"M"
            },
            {
                "name":"绵阳市",
                "key":"M"
            },
            {
                "name":"眉山市",
                "key":"M"
            },
            {
                "name":"苗栗县",
                "key":"M"
            }
        ]
    },
    {
        "title":"N",
        "item":[
            {
                "name":"南京市",
                "key":"N"
            },
            {
                "name":"南通市",
                "key":"N"
            },
            {
                "name":"宁波市",
                "key":"N"
            },
            {
                "name":"南平市",
                "key":"N"
            },
            {
                "name":"宁德市",
                "key":"N"
            },
            {
                "name":"南昌市",
                "key":"N"
            },
            {
                "name":"南阳市",
                "key":"N"
            },
            {
                "name":"南宁市",
                "key":"N"
            },
            {
                "name":"南沙群岛",
                "key":"N"
            },
            {
                "name":"内江市",
                "key":"N"
            },
            {
                "name":"南充市",
                "key":"N"
            },
            {
                "name":"怒江傈僳族自治州",
                "key":"N"
            },
            {
                "name":"那曲地区",
                "key":"N"
            },
            {
                "name":"南投县",
                "key":"N"
            }
        ]
    },
    {
        "title":"P",
        "item":[
            {
                "name":"盘锦市",
                "key":"P"
            },
            {
                "name":"莆田市",
                "key":"P"
            },
            {
                "name":"萍乡市",
                "key":"P"
            },
            {
                "name":"平顶山市",
                "key":"P"
            },
            {
                "name":"攀枝花市",
                "key":"P"
            },
            {
                "name":"普洱市",
                "key":"P"
            },
            {
                "name":"平凉市",
                "key":"P"
            },
            {
                "name":"屏东县",
                "key":"P"
            },
            {
                "name":"澎湖县",
                "key":"P"
            }
        ]
    },
    {
        "title":"Q",
        "item":[
            {
                "name":"秦皇岛市",
                "key":"Q"
            },
            {
                "name":"齐齐哈尔市",
                "key":"Q"
            },
            {
                "name":"七台河市",
                "key":"Q"
            },
            {
                "name":"泉州市",
                "key":"Q"
            },
            {
                "name":"青岛市",
                "key":"Q"
            },
            {
                "name":"潜江市",
                "key":"Q"
            },
            {
                "name":"清远市",
                "key":"Q"
            },
            {
                "name":"钦州市",
                "key":"Q"
            },
            {
                "name":"琼海市",
                "key":"Q"
            },
            {
                "name":"琼中黎族苗族自治县",
                "key":"Q"
            },
            {
                "name":"黔西南布依族苗族自治州",
                "key":"Q"
            },
            {
                "name":"黔东南苗族侗族自治州",
                "key":"Q"
            },
            {
                "name":"黔南布依族苗族自治州",
                "key":"Q"
            },
            {
                "name":"曲靖市",
                "key":"Q"
            },
            {
                "name":"庆阳市",
                "key":"Q"
            }
        ]
    },
    {
        "title":"R",
        "item":[
            {
                "name":"日照市",
                "key":"R"
            },
            {
                "name":"日喀则地区",
                "key":"R"
            }
        ]
    },
    {
        "title":"S",
        "item":[
            {
                "name":"石家庄市",
                "key":"S"
            },
            {
                "name":"朔州市",
                "key":"S"
            },
            {
                "name":"沈阳市",
                "key":"S"
            },
            {
                "name":"四平市",
                "key":"S"
            },
            {
                "name":"松原市",
                "key":"S"
            },
            {
                "name":"双鸭山市",
                "key":"S"
            },
            {
                "name":"绥化市",
                "key":"S"
            },
            {
                "name":"上海市",
                "key":"S"
            },
            {
                "name":"苏州市",
                "key":"S"
            },
            {
                "name":"宿迁市",
                "key":"S"
            },
            {
                "name":"绍兴市",
                "key":"S"
            },
            {
                "name":"宿州市",
                "key":"S"
            },
            {
                "name":"三明市",
                "key":"S"
            },
            {
                "name":"上饶市",
                "key":"S"
            },
            {
                "name":"三门峡市",
                "key":"S"
            },
            {
                "name":"商丘市",
                "key":"S"
            },
            {
                "name":"十堰市",
                "key":"S"
            },
            {
                "name":"随州市",
                "key":"S"
            },
            {
                "name":"神农架林区",
                "key":"S"
            },
            {
                "name":"邵阳市",
                "key":"S"
            },
            {
                "name":"韶关市",
                "key":"S"
            },
            {
                "name":"深圳市",
                "key":"S"
            },
            {
                "name":"汕头市",
                "key":"S"
            },
            {
                "name":"汕尾市",
                "key":"S"
            },
            {
                "name":"三亚市",
                "key":"S"
            },
            {
                "name":"遂宁市",
                "key":"S"
            },
            {
                "name":"山南地区",
                "key":"S"
            },
            {
                "name":"商洛市",
                "key":"S"
            },
            {
                "name":"石嘴山市",
                "key":"S"
            },
            {
                "name":"石河子市",
                "key":"S"
            }
        ]
    },
    {
        "title":"T",
        "item":[
            {
                "name":"天津市",
                "key":"T"
            },
            {
                "name":"唐山市",
                "key":"T"
            },
            {
                "name":"太原市",
                "key":"T"
            },
            {
                "name":"通辽市",
                "key":"T"
            },
            {
                "name":"铁岭市",
                "key":"T"
            },
            {
                "name":"通化市",
                "key":"T"
            },
            {
                "name":"泰州市",
                "key":"T"
            },
            {
                "name":"台州市",
                "key":"T"
            },
            {
                "name":"铜陵市",
                "key":"T"
            },
            {
                "name":"泰安市",
                "key":"T"
            },
            {
                "name":"天门市",
                "key":"T"
            },
            {
                "name":"屯昌县",
                "key":"T"
            },
            {
                "name":"铜仁地区",
                "key":"T"
            },
            {
                "name":"铜川市",
                "key":"T"
            },
            {
                "name":"天水市",
                "key":"T"
            },
            {
                "name":"吐鲁番地区",
                "key":"T"
            },
            {
                "name":"塔城地区",
                "key":"T"
            },
            {
                "name":"图木舒克市",
                "key":"T"
            },
            {
                "name":"台北市",
                "key":"T"
            },
            {
                "name":"台南市",
                "key":"T"
            },
            {
                "name":"台中市",
                "key":"T"
            },
            {
                "name":"桃园县",
                "key":"T"
            },
            {
                "name":"台东县",
                "key":"T"
            }
        ]
    },
    {
        "title":"W",
        "item":[
            {
                "name":"乌海市",
                "key":"W"
            },
            {
                "name":"乌兰察布市",
                "key":"W"
            },
            {
                "name":"无锡市",
                "key":"W"
            },
            {
                "name":"温州市",
                "key":"W"
            },
            {
                "name":"芜湖市",
                "key":"W"
            },
            {
                "name":"潍坊市",
                "key":"W"
            },
            {
                "name":"威海市",
                "key":"W"
            },
            {
                "name":"武汉市",
                "key":"W"
            },
            {
                "name":"梧州市",
                "key":"W"
            },
            {
                "name":"五指山市",
                "key":"W"
            },
            {
                "name":"文昌市",
                "key":"W"
            },
            {
                "name":"万宁市",
                "key":"W"
            },
            {
                "name":"文山壮族苗族自治州",
                "key":"W"
            },
            {
                "name":"渭南市",
                "key":"W"
            },
            {
                "name":"武威市",
                "key":"W"
            },
            {
                "name":"吴忠市",
                "key":"W"
            },
            {
                "name":"乌鲁木齐市",
                "key":"W"
            },
            {
                "name":"五家渠市",
                "key":"W"
            }
        ]
    },
    {
        "title":"X",
        "item":[
            {
                "name":"邢台市",
                "key":"X"
            },
            {
                "name":"忻州市",
                "key":"X"
            },
            {
                "name":"兴安盟",
                "key":"X"
            },
            {
                "name":"锡林郭勒盟",
                "key":"X"
            },
            {
                "name":"徐州市",
                "key":"X"
            },
            {
                "name":"宣城市",
                "key":"X"
            },
            {
                "name":"厦门市",
                "key":"X"
            },
            {
                "name":"新余市",
                "key":"X"
            },
            {
                "name":"新乡市",
                "key":"X"
            },
            {
                "name":"许昌市",
                "key":"X"
            },
            {
                "name":"信阳市",
                "key":"X"
            },
            {
                "name":"襄阳市",
                "key":"X"
            },
            {
                "name":"孝感市",
                "key":"X"
            },
            {
                "name":"咸宁市",
                "key":"X"
            },
            {
                "name":"仙桃市",
                "key":"X"
            },
            {
                "name":"湘潭市",
                "key":"X"
            },
            {
                "name":"湘西土家族苗族自治州",
                "key":"X"
            },
            {
                "name":"西沙群岛",
                "key":"X"
            },
            {
                "name":"西双版纳傣族自治州",
                "key":"X"
            },
            {
                "name":"西安市",
                "key":"X"
            },
            {
                "name":"咸阳市",
                "key":"X"
            },
            {
                "name":"西宁市",
                "key":"X"
            },
            {
                "name":"新竹市",
                "key":"X"
            },
            {
                "name":"新北市",
                "key":"X"
            },
            {
                "name":"新竹县",
                "key":"X"
            },
            {
                "name":"香港岛",
                "key":"X"
            },
            {
                "name":"新界",
                "key":"X"
            }
        ]
    },
    {
        "title":"Y",
        "item":[
            {
                "name":"阳泉市",
                "key":"Y"
            },
            {
                "name":"运城市",
                "key":"Y"
            },
            {
                "name":"营口市",
                "key":"Y"
            },
            {
                "name":"延边朝鲜族自治州",
                "key":"Y"
            },
            {
                "name":"伊春市",
                "key":"Y"
            },
            {
                "name":"盐城市",
                "key":"Y"
            },
            {
                "name":"扬州市",
                "key":"Y"
            },
            {
                "name":"鹰潭市",
                "key":"Y"
            },
            {
                "name":"宜春市",
                "key":"Y"
            },
            {
                "name":"烟台市",
                "key":"Y"
            },
            {
                "name":"宜昌市",
                "key":"Y"
            },
            {
                "name":"岳阳市",
                "key":"Y"
            },
            {
                "name":"益阳市",
                "key":"Y"
            },
            {
                "name":"永州市",
                "key":"Y"
            },
            {
                "name":"阳江市",
                "key":"Y"
            },
            {
                "name":"云浮市",
                "key":"Y"
            },
            {
                "name":"玉林市",
                "key":"Y"
            },
            {
                "name":"宜宾市",
                "key":"Y"
            },
            {
                "name":"雅安市",
                "key":"Y"
            },
            {
                "name":"玉溪市",
                "key":"Y"
            },
            {
                "name":"延安市",
                "key":"Y"
            },
            {
                "name":"榆林市",
                "key":"Y"
            },
            {
                "name":"玉树藏族自治州",
                "key":"Y"
            },
            {
                "name":"银川市",
                "key":"Y"
            },
            {
                "name":"伊犁哈萨克自治州",
                "key":"Y"
            },
            {
                "name":"宜兰县",
                "key":"Y"
            },
            {
                "name":"云林县",
                "key":"Y"
            }
        ]
    },
    {
        "title":"Z",
        "item":[
            {
                "name":"张家口市",
                "key":"Z"
            },
            {
                "name":"镇江市",
                "key":"Z"
            },
            {
                "name":"舟山市",
                "key":"Z"
            },
            {
                "name":"漳州市",
                "key":"Z"
            },
            {
                "name":"淄博市",
                "key":"Z"
            },
            {
                "name":"枣庄市",
                "key":"Z"
            },
            {
                "name":"郑州市",
                "key":"Z"
            },
            {
                "name":"周口市",
                "key":"Z"
            },
            {
                "name":"驻马店市",
                "key":"Z"
            },
            {
                "name":"株洲市",
                "key":"Z"
            },
            {
                "name":"张家界市",
                "key":"Z"
            },
            {
                "name":"珠海市",
                "key":"Z"
            },
            {
                "name":"湛江市",
                "key":"Z"
            },
            {
                "name":"肇庆市",
                "key":"Z"
            },
            {
                "name":"中山市",
                "key":"Z"
            },
            {
                "name":"中沙群岛的岛礁及其海域",
                "key":"Z"
            },
            {
                "name":"重庆市",
                "key":"Z"
            },
            {
                "name":"自贡市",
                "key":"Z"
            },
            {
                "name":"资阳市",
                "key":"Z"
            },
            {
                "name":"遵义市",
                "key":"Z"
            },
            {
                "name":"昭通市",
                "key":"Z"
            },
            {
                "name":"张掖市",
                "key":"Z"
            },
            {
                "name":"中卫市",
                "key":"Z"
            },
            {
                "name":"彰化县",
                "key":"Z"
            }
        ]
    },
    {
        "title":"其他",
        "item":[
            {
                "name":"衢州市",
                "key":"其他"
            },
            {
                "name":"亳州市",
                "key":"其他"
            },
            {
                "name":"濮阳市",
                "key":"其他"
            },
            {
                "name":"漯河市",
                "key":"其他"
            },
            {
                "name":"儋州市",
                "key":"其他"
            },
            {
                "name":"泸州市",
                "key":"其他"
            }
        ]
    }
];

module.exports = city;